// <auto-generated />
namespace YackeenBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedInitialCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedInitialCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201910101722352_SeedInitialCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
